name: Deploy to GitHub Pages (npm)

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

env:
  ELEVENTY_NOTES_PATH_PREFIX: 'eleventy-notes'

# run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

jobs:
  setup:
    name: Setup and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        # with:
        #   fetch-depth: 0
      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install --prefix .app
      - name: Build
        run: npm run build --prefix .app
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .app/dist

  deploy:
    name: Deploy
    needs: setup
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
